### read all products
GET http://localhost:3000/products


### read a products by id
GET http://localhost:3000/products/"hp"


###create new product
POST http://localhost:3000/products
Content-Type: application/json

{
    "pid":2,
    "name":"computer",
    "brand":"hp",
    "price":60000
}


###update a product
PUT http://localhost:3000/products
Content-Type: application/json

{
    "pid":1,
    "name":"phone",
    "brand":"samsung",
    "price":30000
}


###delete a product by id
DELETE http://localhost:3000/products/1